### ISSUE TITLE
What is header property for?

### ISSUE THREAD

**Issue by garak** [p-chess/chess#15]
We got an `$header` property, I was wondering if we could remove it.
I see that is just an array holding two keys: "setUp" and "FEN", but it's not clear to me how such informations can be useful.

**Comment by akondas** [comment]
Looks like it is used only in `pgn` method, for me we can remove it

**Comment by garak** [comment]
I looked more deeply and it looks like header is indeed a standard of [Portable Game Notation](https://en.wikipedia.org/wiki/Portable_Game_Notation).

So I guess that we should keep it (and maybe refactoring it to an object)

**Comment by garak** [comment]
With a second look, I think that keeping such information in a chess engine is bit out of scope.
I changed my mind and now I think it's better to remove both header property and methods about PGN (currently, we only use PGN in Validation class, with method called by anything but tests)

**Comment by akondas** [comment]
I will trust you on this, because you have explored this subject more than I have :wink:

**Comment by akondas** [comment]
I can say that this pgn output could be a separate project :sunglasses: :thinking:
