### ISSUE TITLE
ignore composer.lock

### ISSUE THREAD

**Issue by garak** [p-chess/chess#29]
I think that composer.lock should be ignored, since this is a library (not a product).
Scenario: I was about to update vendors in my local copy, then I realized that such action would update composer.lock to *my environment* (for example, I use php 7.4 but this lib is compatible with php ^7.2).

The only drawback I see is that CI could be a bit slower, since it can't rely on composer.lock while installing vendor libs.

**Comment by akondas** [comment]
All in all i'm not convinced because when downloading this package as a dependency, composer.lock is ignored anyway... 

As for the local build, you can always add Dockerfile and run development through it. What do you think about it?

**Comment by garak** [comment]
Well, all libraries I see around ignore composer.lock
I guess it's a way to ease possible contributions. I know that everyone should be able to setup docker nowadays, but it's anyway a barrier.

**Comment by akondas** [comment]
ok, let's remove it :+1:
