### ISSUE TITLE
Problem with some types in Move

### ISSUE THREAD

**Issue by garak** [p-chess/chess#3]
Following properties in Move are integers: `from`, `to`, `flags`.
Anyway, the `prettyMove` method in `Chess` is chaning such properties to strings.
Problem is also present in original library, so we need to investigate the logic.

For what I understand, `from` and `to` are indicating the squares where the move is starting and engind, and there's two possible representations: as integers (from 0 to 119) and in string notation of rank and file (e.g. `e2`). We need to understand where/how to apply such different representations (for example, I guess that in history it makes more sense the latter, but mabye the former can be used when undoing?)

For `flags`, I've got no clue.

**Comment by garak** [comment]
My idea about this is: remove completely `prettyMove` method and add a `__toString` method to Move. Such method will output the move in algebraic notation

**Comment by garak** [comment]
With a deeper look, I think that we should simply remove the parts currently marked with "TODO" in `prettyMove` method (so, we'll keep `to`, `from`, `flags` as they are).

With such change, we can re-raise phpstan level to 3.

**Comment by akondas** [comment]
Going back to the flags, can we write them somehow? Maybe in another repo (after all it is a port) it will be written better: https://github.com/jhlywa/chess.js

**Comment by garak** [comment]
I think that current implementation of flags is just a (wrong) way to hide some complexity. It aims to keep 7 properties into a single one.
I guess that it would be better to go explicit: remove flags and add such properties to Move object.

**Comment by garak** [comment]
Got a PR ready for this, just waiting other to be merged
